### ISSUE TITLE
Nikon D40x Raw Tone Curve file

### ISSUE THREAD

**Issue by sstorskon24** [Doug-Pardee/LightZombie#16]
Hi!
I am looking for the Nikon D40x Raw Tone Curve file. Thanks! 

Stephani

**Comment by Doug-Pardee** [comment]
The D40x Raw Tone Curve is part of the original LightZone 3.9 distribution, but the filename erroneously contains a small "x" and therefore only works on Windows. Download the file from https://github.com/Aries85/LightZone/raw/master/lightcrafts/resources/com/lightcrafts/ui/editor/assoc/resources/NIKON%20D40x.lzt into your LightZone/Templates folder, and rename it to CameraDefault;NIKON D40X.lzt. Be sure that the "CameraDefault;" part that you add is capitalized that way, and that the X in D40X is also capitalized.

I've put in an issue report at the LightZone Project (https://github.com/Aries85/LightZone), which is now the active project. The LightZombie project is no longer active.
