### ISSUE TITLE
Is there any effort to push for an open-source release?

### ISSUE THREAD

**Issue by mattdm** [Doug-Pardee/LightZombie#5]
Is there any effort to push for an open-source release? A kickstarter project, say?

**Comment by texandrews** [comment]
On 11/19/2011 3:37 PM, mattdm wrote:

> Is there any effort to push for an open-source release? A kickstarter project, say?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Doug-Pardee/LightZombie/issues/5
> Matt, CONFIDENTIAL:

Yes, but very very very quietly.  The creator and man with the 
Intellectual Property Rights, Fabio Riccardi, has indeed been 
considering this option according to a private email he sent to an Irish 
user.  But his response to me was pretty brief, almost to the point of 
curt.  Things I've learned just in the last few days coupled with things 
I've put together over the last 5 years suggest a possibly unstable person.

So the LAST thing we want to do right now is push him.  If you are 
tech-competetent, then we need you and that's why we have the Github 
thing going and why we have launched an LZ support website, 
www.lightzombie.org.   Please register for our forums there.  Right now 
our aim is just to keep the software alive and to produce new raw 
profiles.  Our ideal is indeed for this thing to eventually go open source.

Right now Fabio works for Apple, as of September.  This also makes this 
situation delicate.

Please stay in touch with us. Thanks for getting in touch

tex

**Comment by Doug-Pardee** [comment]
Matt,

While we'd love to see LZ as open-source, Tex and I both feel that the timing isn't right. It appears that Fabio doesn't want to hear anything more about LightZone for the moment, and I can understand that. One indication: his total destruction of the Light Crafts site, including its forums, without so much as a note saying, "we're out of business." And open-sourcing is a fairly precipitous act — there's no going back — so it's a big decision to ask of him. I don't think Fabio is going to be at all receptive right now.

Part of the thinking behind the LightZombie project is to keep LZ alive and thriving long enough for Fabio to get his life back in order, and for him to come to terms with the death of Light Crafts. Then we might be able to persuade him that open-sourcing is a reasonable thing to do.

-- Doug Pardee   dougpardee@yahoo.com

**Comment by mattdm** [comment]
Hmmm, okay, thanks. I've signed up for the forum, and I'll keep my eyes open
for further developments.

On Sat, Nov 19, 2011 at 01:14:52PM -0800, texandrews wrote:

> On 11/19/2011 3:37 PM, mattdm wrote:
> 
> > Is there any effort to push for an open-source release? A kickstarter project, say?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Doug-Pardee/LightZombie/issues/5
> > Matt, CONFIDENTIAL:
> 
> Yes, but very very very quietly.  The creator and man with the 
> Intellectual Property Rights, Fabio Riccardi, has indeed been 
> considering this option according to a private email he sent to an Irish 
> user.  But his response to me was pretty brief, almost to the point of 
> curt.  Things I've learned just in the last few days coupled with things 
> I've put together over the last 5 years suggest a possibly unstable person.
> 
> So the LAST thing we want to do right now is push him.  If you are 
> tech-competetent, then we need you and that's why we have the Github 
> thing going and why we have launched an LZ support website, 
> www.lightzombie.org.   Please register for our forums there.  Right now 
> our aim is just to keep the software alive and to produce new raw 
> profiles.  Our ideal is indeed for this thing to eventually go open source.
> 
> Right now Fabio works for Apple, as of September.  This also makes this 
> situation delicate.
> 
> Please stay in touch with us. Thanks for getting in touch
> 
> tex
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Doug-Pardee/LightZombie/issues/5#issuecomment-2800971

## 

Matthew Miller           mattdm@mattdm.org          http://mattdm.org/

**Comment by mattdm** [comment]
Thanks for the info. I'll keep my eyes out for further developments.

On Sat, Nov 19, 2011 at 01:16:34PM -0800, Doug Pardee wrote:

> Matt,
> 
> While we'd love to see LZ as open-source, Tex and I both feel that the timing isn't right. It appears that Fabio doesn't want to hear anything more about LightZone for the moment, and I can understand that. One indication: his total destruction of the Light Crafts site, including its forums, without so much as a note saying, "we're out of business." And open-sourcing is a fairly precipitous act — there's no going back — so it's a big decision to ask of him. I don't think Fabio is going to be at all receptive right now.
> 
> Part of the thinking behind the LightZombie project is to keep LZ alive and thriving long enough for Fabio to get his life back in order, and for him to come to terms with the death of Light Crafts. Then we might be able to persuade him that open-sourcing is a reasonable thing to do.
> 
> -- Doug Pardee   dougpardee@yahoo.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Doug-Pardee/LightZombie/issues/5#issuecomment-2800976

## 

Matthew Miller           mattdm@mattdm.org          http://mattdm.org/
