### ISSUE TITLE
would like to use fujifilm x10

### ISSUE THREAD

**Issue by solsang** [Doug-Pardee/LightZombie#8]
this camera is just released and already a classic, 
i plan working with it as my only camera next year if i have to give up on lx5 and have a friend with lightzone also wanting to use it

**Comment by Doug-Pardee** [comment]
The Mac version of dcraw 9.12, with X10 support, is available from https://github.com/Doug-Pardee/LightZombie/raw/Unstable/dcraw/Mac/dcraw -- be sure to "chmod +x" it after downloading. This file is in "beta" status, so do let us know if there are any problems with it.

A preliminary version of the X10 Raw Tone Curve is available from https://github.com/Doug-Pardee/LightZombie/raw/master/Templates/CameraRawProfiles/Fujifilm/CameraDefault;FUJIFILM%20X10.lzt -- this file was not created from a reliable reference image and I expect that a newer, more exact version will be available after DPReview issues its review of the X10.

I'm going to mark this issue "closed." If you have any trouble with the two files, feel free to re-open it.
